README: Add instruction to update submodules
Otherwise the default build instruction will fail on first build:

rockhopper:~/src/salus (main)$ bazel build //:salus-all
ERROR: Error computing the main repository mapping: Label
'//sbi-rs:deps.bzl' is invalid because 'sbi-rs' is not a package;
perhaps you meant to put the colon here: '//:sbi-rs/deps.bzl'?

Signed-off-by: Rob Bradford <rbradford@rivosinc.com>